#!/usr/bin/env node

'use strict';

const app = require('../index');
const http = require('http');

const port = process.env.PORT || 5000;
app.set('port', port);
http.createServer(app).listen(port, () => {
  /* eslint-disable no-console */
  console.log(`The app is running at http://localhost:${port}/`);
});
